package proposal

import (
	"context"
	"errors"
	"fmt"

	"github.com/Wayne997035/wayneblacktea/internal/db"
	"github.com/Wayne997035/wayneblacktea/internal/pgconv"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

// pgxBeginTx is the subset of pgxpool.Pool used by BatchConfirm so we can
// inject a fake in tests without importing pgxpool directly.
type pgxBeginTx interface {
	Begin(ctx context.Context) (pgx.Tx, error)
}

// Store handles all database operations for the Proposal bounded context.
type Store struct {
	q           *db.Queries
	dbtx        db.DBTX // retained for ad-hoc queries not generated by sqlc
	workspaceID pgtype.UUID
	// pool is retained so BatchConfirm can begin its own transaction.
	// nil when Store was constructed from a tx via WithTx.
	pool pgxBeginTx
}

// NewStore returns a Store backed by the given DBTX scoped to the optional
// workspace. nil workspaceID = legacy unscoped mode.
func NewStore(dbtx db.DBTX, workspaceID *uuid.UUID) *Store {
	var pool pgxBeginTx
	if p, ok := dbtx.(pgxBeginTx); ok {
		pool = p
	}
	return &Store{q: db.New(dbtx), dbtx: dbtx, workspaceID: pgconv.ToUUID(workspaceID), pool: pool}
}

// WithTx returns a Store bound to tx, preserving the workspace scope.
// The pool reference is intentionally dropped — tx-scoped stores must not
// begin nested transactions.
func (s *Store) WithTx(tx pgx.Tx) *Store {
	return &Store{q: s.q.WithTx(tx), dbtx: tx, workspaceID: s.workspaceID}
}

// MaxPayloadBytes bounds CreateParams.Payload — [F981-05]. Per-field caps in
// the mcp-side decoders (decodeGoalParams/decodeProjectParams,
// internal/mcp/tools_proposal.go) and the seam-side decoders
// (accept_decode.go) already keep a legitimate goal/project payload well
// under this: title/area 512 B each + description 64 KB sums to well under
// 128 KB. This is a fail-closed backstop at the write path itself — the
// gap it closes is that nothing checked len(p.Payload) before this, so an
// oversized payload from a prompt-injected agent (propose_goal/
// propose_project MCP tools, the only confirmed callers of Create at time
// of writing) reached pending_proposals unbounded before any accept-time
// decoder cap ever ran.
//
// Exported (not package-private) so internal/storage/sqlite's ProposalStore
// — a separate Create implementation for the dual-backend seam — enforces
// the identical byte limit from one source of truth instead of a duplicated
// magic number that could silently drift between the two backends.
const MaxPayloadBytes = 128 * 1024

// Create records a new pending proposal. Payload is opaque JSON; the caller is
// responsible for marshalling the entity-specific shape.
//
// If CreateParams.WorkspaceID is set, it overrides the store's workspace scope
// (used e.g. for tests or rare cross-workspace proposals). When nil, the
// store's configured workspace is used.
func (s *Store) Create(ctx context.Context, p CreateParams) (*db.PendingProposal, error) {
	// [F981-05] fail-closed size guard before any DB call — see
	// MaxPayloadBytes' doc comment for why 128 KB and what it protects.
	if len(p.Payload) > MaxPayloadBytes {
		return nil, fmt.Errorf("creating proposal: payload %d bytes exceeds %d byte limit: %w",
			len(p.Payload), MaxPayloadBytes, ErrPayloadTooLarge)
	}
	ws := s.workspaceID
	if p.WorkspaceID != nil {
		ws = pgconv.ToUUID(p.WorkspaceID)
	}
	row, err := s.q.CreatePendingProposal(ctx, db.CreatePendingProposalParams{
		WorkspaceID: ws,
		Type:        string(p.Type),
		Payload:     p.Payload,
		ProposedBy:  pgconv.ToText(p.ProposedBy),
	})
	if err != nil {
		return nil, fmt.Errorf("creating proposal: %w", err)
	}
	return &row, nil
}

// Get returns a single proposal by ID. Returns ErrNotFound when missing.
func (s *Store) Get(ctx context.Context, id uuid.UUID) (*db.PendingProposal, error) {
	row, err := s.q.GetPendingProposal(ctx, db.GetPendingProposalParams{
		ID:          id,
		WorkspaceID: s.workspaceID,
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("getting proposal %s: %w", id, err)
	}
	return &row, nil
}

// ListPending returns all proposals awaiting user resolution, newest first.
//
// [F170-06] Contract unchanged: the query gained row_limit / row_offset and
// this method passes db.UnboundedRowLimit, so the HTTP handler, the dashboard
// and the scheduler keep receiving every pending row. ListPendingPage is the
// capped variant the MCP tool uses.
func (s *Store) ListPending(ctx context.Context) ([]db.PendingProposal, error) {
	return s.ListPendingPage(ctx, db.UnboundedRowLimit, 0)
}

// ListPendingPage returns at most limit pending proposals starting at offset,
// newest first — [F170-06].
func (s *Store) ListPendingPage(ctx context.Context, limit, offset int32) ([]db.PendingProposal, error) {
	rows, err := s.q.ListPendingProposals(ctx, db.ListPendingProposalsParams{
		WorkspaceID: s.workspaceID,
		RowLimit:    db.ClampRowLimit(limit),
		RowOffset:   db.ClampRowOffset(offset),
	})
	if err != nil {
		return nil, fmt.Errorf("listing pending proposals: %w", err)
	}
	if rows == nil {
		// list endpoints MUST return [] not null — MCP's list_pending_proposals
		// (tools_proposal.go handleListPendingProposals) serializes this slice
		// directly with no handler-level guard of its own.
		rows = []db.PendingProposal{}
	}
	return rows, nil
}

// ListAll returns all proposals of the given type regardless of status,
// newest first, up to limit rows. Status filtering is done in Go by the caller.
// Using parameterized query prevents SQL injection — proposalType and limit are
// bound as query parameters, never interpolated into the SQL string.
func (s *Store) ListAll(ctx context.Context, proposalType string, limit int32) ([]db.PendingProposal, error) {
	const listAllQ = `SELECT id, workspace_id, type, payload, status, proposed_by, created_at, resolved_at, reason
		FROM pending_proposals
		WHERE type = $1
		  AND ($2::uuid IS NULL OR workspace_id = $2)
		ORDER BY created_at DESC
		LIMIT $3`
	rawRows, err := s.dbtx.Query(ctx, listAllQ, proposalType, s.workspaceID, limit)
	if err != nil {
		return nil, fmt.Errorf("listing all proposals: %w", err)
	}
	defer rawRows.Close()
	var items []db.PendingProposal
	for rawRows.Next() {
		var i db.PendingProposal
		if err := rawRows.Scan(
			&i.ID, &i.WorkspaceID, &i.Type, &i.Payload, &i.Status,
			&i.ProposedBy, &i.CreatedAt, &i.ResolvedAt, &i.Reason,
		); err != nil {
			return nil, fmt.Errorf("scanning proposal row: %w", err)
		}
		items = append(items, i)
	}
	if err := rawRows.Err(); err != nil {
		return nil, fmt.Errorf("iterating proposals: %w", err)
	}
	return items, nil
}

// Resolve marks a pending proposal as accepted or rejected. Already-resolved
// proposals return ErrNotFound (idempotent rather than overwrite).
func (s *Store) Resolve(ctx context.Context, id uuid.UUID, status Status) (*db.PendingProposal, error) {
	if status != StatusAccepted && status != StatusRejected {
		return nil, fmt.Errorf("resolve: invalid status %q (want accepted or rejected)", status)
	}
	row, err := s.q.ResolvePendingProposal(ctx, db.ResolvePendingProposalParams{
		ID:          id,
		Status:      string(status),
		WorkspaceID: s.workspaceID,
	})
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, ErrNotFound
		}
		return nil, fmt.Errorf("resolving proposal %s: %w", id, err)
	}
	return &row, nil
}

// BatchConfirm resolves multiple proposals inside a single Postgres transaction.
// If any individual Resolve fails (not found, already resolved, DB error) the
// whole transaction is rolled back and all entries are reported as failed.
// Callers must have already validated ids (len 1–100) and status.
func (s *Store) BatchConfirm(ctx context.Context, ids []uuid.UUID, status Status) (BatchConfirmResult, error) {
	if status != StatusAccepted && status != StatusRejected {
		return BatchConfirmResult{}, fmt.Errorf("batch confirm: invalid status %q", status)
	}
	if s.pool == nil {
		return BatchConfirmResult{}, fmt.Errorf("batch confirm: store has no pool (tx-scoped store cannot begin transaction)")
	}

	tx, err := s.pool.Begin(ctx)
	if err != nil {
		return BatchConfirmResult{}, fmt.Errorf("batch confirm: begin tx: %w", err)
	}
	defer func() { _ = tx.Rollback(ctx) }() // no-op if committed

	txStore := s.WithTx(tx)
	results := make([]BatchItemResult, 0, len(ids))

	for _, id := range ids {
		_, err := txStore.Resolve(ctx, id, status)
		if err != nil {
			// Roll back the whole batch on any single failure.
			_ = tx.Rollback(ctx)
			failed := make([]BatchItemResult, 0, len(ids))
			for _, fid := range ids {
				msg := ""
				if fid == id {
					msg = err.Error()
				} else {
					msg = "rolled back due to sibling failure"
				}
				failed = append(failed, BatchItemResult{ID: fid.String(), OK: false, ErrMsg: msg})
			}
			return BatchConfirmResult{Results: failed, Failed: len(ids)}, nil
		}
		results = append(results, BatchItemResult{ID: id.String(), OK: true})
	}

	if err := tx.Commit(ctx); err != nil {
		return BatchConfirmResult{}, fmt.Errorf("batch confirm: commit: %w", err)
	}
	return BatchConfirmResult{Results: results, Accepted: len(ids)}, nil
}
