-- SQLite-dialect twin of migrations/000015_workspace_id_backfill.up.sql.
--
-- Usage: see docs/operations.md → "WORKSPACE_ID Backfill (migration 000015)"
-- → "SQLite self-hosters". Copy to /tmp and sed-substitute the sentinel
-- before running — do NOT edit this file in place.
--
-- Sentinel: 00000000-0000-0000-0000-000000000001

UPDATE goals             SET workspace_id = '00000000-0000-0000-0000-000000000001' WHERE workspace_id IS NULL;
UPDATE projects          SET workspace_id = '00000000-0000-0000-0000-000000000001' WHERE workspace_id IS NULL;
UPDATE tasks             SET workspace_id = '00000000-0000-0000-0000-000000000001' WHERE workspace_id IS NULL;
UPDATE activity_log      SET workspace_id = '00000000-0000-0000-0000-000000000001' WHERE workspace_id IS NULL;
UPDATE repos             SET workspace_id = '00000000-0000-0000-0000-000000000001' WHERE workspace_id IS NULL;
UPDATE decisions         SET workspace_id = '00000000-0000-0000-0000-000000000001' WHERE workspace_id IS NULL;
UPDATE session_handoffs  SET workspace_id = '00000000-0000-0000-0000-000000000001' WHERE workspace_id IS NULL;
UPDATE knowledge_items   SET workspace_id = '00000000-0000-0000-0000-000000000001' WHERE workspace_id IS NULL;
UPDATE concepts          SET workspace_id = '00000000-0000-0000-0000-000000000001' WHERE workspace_id IS NULL;
UPDATE review_schedule   SET workspace_id = '00000000-0000-0000-0000-000000000001' WHERE workspace_id IS NULL;
UPDATE pending_proposals SET workspace_id = '00000000-0000-0000-0000-000000000001' WHERE workspace_id IS NULL;
