// Package cli contains the logic for the wbt CLI subcommands. It is extracted
// from cmd/wbt/main.go so that the pure helper functions can be unit-tested
// without subprocess execution or file I/O.
package cli

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"strings"
)

// DBConfig holds the database configuration collected during init.
type DBConfig struct {
	StorageBackend string
	DatabaseURL    string
	SQLitePath     string
}

// GenerateEnvFile returns the contents of the .env file produced by wbt init.
//
// The output contains:
//   - API_KEY, PORT, STORAGE_BACKEND (always present)
//   - DATABASE_URL (postgres backend only)
//   - SQLITE_PATH (sqlite backend only)
//   - ALLOWED_ORIGINS defaulting to localhost on the given port
//   - Commented hints for optional AI provider keys
func GenerateEnvFile(apiKey, port string, db DBConfig) string {
	var sb strings.Builder
	sb.WriteString("# wayneblacktea — generated by wbt init\n")
	writeEnvLine(&sb, "API_KEY", apiKey)
	writeEnvLine(&sb, "PORT", port)
	writeEnvLine(&sb, "STORAGE_BACKEND", db.StorageBackend)
	if db.DatabaseURL != "" {
		writeEnvLine(&sb, "DATABASE_URL", db.DatabaseURL)
	}
	if db.SQLitePath != "" {
		writeEnvLine(&sb, "SQLITE_PATH", db.SQLitePath)
	}
	// ALLOWED_ORIGINS: defaults to localhost for local dev.
	// In production (APP_ENV=production) this must be set to your public domain.
	allowedOrigins := fmt.Sprintf("http://localhost:%s,http://127.0.0.1:%s", port, port)
	writeEnvLine(&sb, "ALLOWED_ORIGINS", allowedOrigins)
	sb.WriteString("\n# Optional AI features. Leave unset for memory-only mode.\n")
	writeOptionalEnvLine(&sb, "GEMINI_API_KEY", "knowledge embeddings / dedup")
	writeOptionalEnvLine(&sb, "GROQ_API_KEY", "Discord /analyze")
	writeOptionalEnvLine(&sb, "CLAUDE_API_KEY", "advanced automation: classifier / reflection / snapshots")
	return sb.String()
}

// writeEnvLine appends a KEY=value line, double-quoting the value when it
// contains any character that godotenv would otherwise interpret as syntax:
//   - space / tab: would split the line
//   - '#': would start a comment, silently truncating the value
//   - '"' / '\\': would corrupt the parser
//   - newline / carriage return: would break the file structure
//
// This prevents silent credential corruption when an API key or DSN contains
// '#' (a common character in randomly-generated secrets) or other shell-special
// chars.
func writeEnvLine(sb *strings.Builder, key, value string) {
	if strings.ContainsAny(value, " \t#\"\\\r\n") {
		fmt.Fprintf(sb, "%s=%q\n", key, value)
	} else {
		fmt.Fprintf(sb, "%s=%s\n", key, value)
	}
}

// writeOptionalEnvLine emits a two-line block: a comment describing the
// purpose, then a fully-commented assignment the user can uncomment.
func writeOptionalEnvLine(sb *strings.Builder, key, note string) {
	fmt.Fprintf(sb, "# %s\n# %s=\n", note, key)
}

// RandomHex generates n cryptographically random bytes encoded as hex.
func RandomHex(n int) (string, error) {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		return "", fmt.Errorf("crypto/rand: %w", err)
	}
	return hex.EncodeToString(b), nil
}

// ResolveAllowedOrigins determines the CORS allowed-origins string for the
// .env file. This is the wbt-init variant (reads env vars directly so it can
// be tested without subprocess wiring).
//
// Rules (mirrors cmd/server resolveAllowedOrigins):
//   - ALLOWED_ORIGINS="*" is always rejected.
//   - ALLOWED_ORIGINS non-empty → returned as-is.
//   - ALLOWED_ORIGINS empty + APP_ENV="production" → error.
//   - ALLOWED_ORIGINS empty + any other APP_ENV → default to localhost on port.
func ResolveAllowedOrigins(allowedOrigins, appEnv, port string) (string, error) {
	raw := strings.TrimSpace(allowedOrigins)
	env := strings.TrimSpace(appEnv)

	if raw == "*" {
		return "", fmt.Errorf("ALLOWED_ORIGINS must not be '*' when AllowCredentials=true; set explicit origins")
	}
	if raw != "" {
		return raw, nil
	}
	if env == "production" {
		return "", fmt.Errorf("ALLOWED_ORIGINS must be set in production (APP_ENV=production); got empty value")
	}
	return fmt.Sprintf("http://localhost:%s,http://127.0.0.1:%s", port, port), nil
}
