// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: decision.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDecision = `-- name: CreateDecision :one
INSERT INTO decisions (project_id, repo_name, title, context, decision, rationale, alternatives, workspace_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, project_id, repo_name, title, context, decision, rationale, alternatives, created_at, workspace_id
`

type CreateDecisionParams struct {
	ProjectID    pgtype.UUID `json:"project_id"`
	RepoName     pgtype.Text `json:"repo_name"`
	Title        string      `json:"title"`
	Context      string      `json:"context"`
	Decision     string      `json:"decision"`
	Rationale    string      `json:"rationale"`
	Alternatives pgtype.Text `json:"alternatives"`
	WorkspaceID  pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) CreateDecision(ctx context.Context, arg CreateDecisionParams) (Decision, error) {
	row := q.db.QueryRow(ctx, createDecision,
		arg.ProjectID,
		arg.RepoName,
		arg.Title,
		arg.Context,
		arg.Decision,
		arg.Rationale,
		arg.Alternatives,
		arg.WorkspaceID,
	)
	var i Decision
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RepoName,
		&i.Title,
		&i.Context,
		&i.Decision,
		&i.Rationale,
		&i.Alternatives,
		&i.CreatedAt,
		&i.WorkspaceID,
	)
	return i, err
}

const listAllDecisions = `-- name: ListAllDecisions :many
SELECT id, project_id, repo_name, title, context, decision, rationale, alternatives, created_at, workspace_id FROM decisions
WHERE ($1::uuid IS NULL OR workspace_id = $1)
ORDER BY created_at DESC
LIMIT $2
`

type ListAllDecisionsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	LimitN      int32       `json:"limit_n"`
}

func (q *Queries) ListAllDecisions(ctx context.Context, arg ListAllDecisionsParams) ([]Decision, error) {
	rows, err := q.db.Query(ctx, listAllDecisions, arg.WorkspaceID, arg.LimitN)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Decision
	for rows.Next() {
		var i Decision
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.RepoName,
			&i.Title,
			&i.Context,
			&i.Decision,
			&i.Rationale,
			&i.Alternatives,
			&i.CreatedAt,
			&i.WorkspaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDecisionsByProject = `-- name: ListDecisionsByProject :many
SELECT id, project_id, repo_name, title, context, decision, rationale, alternatives, created_at, workspace_id FROM decisions
WHERE project_id = $1
  AND ($2::uuid IS NULL OR workspace_id = $2)
ORDER BY created_at DESC
LIMIT $3
`

type ListDecisionsByProjectParams struct {
	ProjectID   pgtype.UUID `json:"project_id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	LimitN      int32       `json:"limit_n"`
}

func (q *Queries) ListDecisionsByProject(ctx context.Context, arg ListDecisionsByProjectParams) ([]Decision, error) {
	rows, err := q.db.Query(ctx, listDecisionsByProject, arg.ProjectID, arg.WorkspaceID, arg.LimitN)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Decision
	for rows.Next() {
		var i Decision
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.RepoName,
			&i.Title,
			&i.Context,
			&i.Decision,
			&i.Rationale,
			&i.Alternatives,
			&i.CreatedAt,
			&i.WorkspaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDecisionsByRepo = `-- name: ListDecisionsByRepo :many
SELECT id, project_id, repo_name, title, context, decision, rationale, alternatives, created_at, workspace_id FROM decisions
WHERE repo_name = $1
  AND ($2::uuid IS NULL OR workspace_id = $2)
ORDER BY created_at DESC
LIMIT $3
`

type ListDecisionsByRepoParams struct {
	RepoName    pgtype.Text `json:"repo_name"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	LimitN      int32       `json:"limit_n"`
}

func (q *Queries) ListDecisionsByRepo(ctx context.Context, arg ListDecisionsByRepoParams) ([]Decision, error) {
	rows, err := q.db.Query(ctx, listDecisionsByRepo, arg.RepoName, arg.WorkspaceID, arg.LimitN)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Decision
	for rows.Next() {
		var i Decision
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.RepoName,
			&i.Title,
			&i.Context,
			&i.Decision,
			&i.Rationale,
			&i.Alternatives,
			&i.CreatedAt,
			&i.WorkspaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
