// Package db contains sqlc-generated query and model types for PostgreSQL.
// All other files in this package are generated by sqlc — do not edit by hand.
// Run `task sqlc` from the build/ directory to regenerate after query/migration changes.
package db
