// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gtd.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeTask = `-- name: CompleteTask :one
UPDATE tasks SET status = 'completed', artifact = $2, updated_at = NOW()
WHERE id = $1 RETURNING id, project_id, title, description, status, priority, assignee, due_date, artifact, created_at, updated_at
`

type CompleteTaskParams struct {
	ID       uuid.UUID   `json:"id"`
	Artifact pgtype.Text `json:"artifact"`
}

func (q *Queries) CompleteTask(ctx context.Context, arg CompleteTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, completeTask, arg.ID, arg.Artifact)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Assignee,
		&i.DueDate,
		&i.Artifact,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countCompletedTasksThisWeek = `-- name: CountCompletedTasksThisWeek :one
SELECT COUNT(*) FROM tasks
WHERE status = 'completed'
  AND updated_at >= date_trunc('week', NOW())
  AND updated_at < date_trunc('week', NOW()) + interval '1 week'
`

func (q *Queries) CountCompletedTasksThisWeek(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCompletedTasksThisWeek)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTotalActiveTasks = `-- name: CountTotalActiveTasks :one
SELECT COUNT(*) FROM tasks WHERE status IN ('pending', 'in_progress')
`

func (q *Queries) CountTotalActiveTasks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTotalActiveTasks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createActivityLog = `-- name: CreateActivityLog :one
INSERT INTO activity_log (actor, project_id, action, notes)
VALUES ($1, $2, $3, $4)
RETURNING id, actor, project_id, action, notes, created_at
`

type CreateActivityLogParams struct {
	Actor     string      `json:"actor"`
	ProjectID pgtype.UUID `json:"project_id"`
	Action    string      `json:"action"`
	Notes     pgtype.Text `json:"notes"`
}

func (q *Queries) CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) (ActivityLog, error) {
	row := q.db.QueryRow(ctx, createActivityLog,
		arg.Actor,
		arg.ProjectID,
		arg.Action,
		arg.Notes,
	)
	var i ActivityLog
	err := row.Scan(
		&i.ID,
		&i.Actor,
		&i.ProjectID,
		&i.Action,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const createGoal = `-- name: CreateGoal :one
INSERT INTO goals (title, description, area, due_date)
VALUES ($1, $2, $3, $4)
RETURNING id, title, description, status, area, due_date, created_at, updated_at
`

type CreateGoalParams struct {
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	Area        pgtype.Text        `json:"area"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, createGoal,
		arg.Title,
		arg.Description,
		arg.Area,
		arg.DueDate,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Area,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (goal_id, name, title, description, area, priority)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, goal_id, name, title, description, status, area, priority, created_at, updated_at
`

type CreateProjectParams struct {
	GoalID      pgtype.UUID `json:"goal_id"`
	Name        string      `json:"name"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	Area        string      `json:"area"`
	Priority    int32       `json:"priority"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.GoalID,
		arg.Name,
		arg.Title,
		arg.Description,
		arg.Area,
		arg.Priority,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.Name,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Area,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (project_id, title, description, priority, assignee, due_date)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, project_id, title, description, status, priority, assignee, due_date, artifact, created_at, updated_at
`

type CreateTaskParams struct {
	ProjectID   pgtype.UUID        `json:"project_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	Priority    int32              `json:"priority"`
	Assignee    pgtype.Text        `json:"assignee"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.Assignee,
		arg.DueDate,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Assignee,
		&i.DueDate,
		&i.Artifact,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllPendingTasks = `-- name: GetAllPendingTasks :many
SELECT id, project_id, title, description, status, priority, assignee, due_date, artifact, created_at, updated_at FROM tasks
WHERE status IN ('pending', 'in_progress')
ORDER BY priority ASC, created_at ASC
`

func (q *Queries) GetAllPendingTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.Query(ctx, getAllPendingTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.Assignee,
			&i.DueDate,
			&i.Artifact,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectByName = `-- name: GetProjectByName :one
SELECT id, goal_id, name, title, description, status, area, priority, created_at, updated_at FROM projects WHERE name = $1 LIMIT 1
`

func (q *Queries) GetProjectByName(ctx context.Context, name string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByName, name)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.Name,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Area,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTasksByProject = `-- name: GetTasksByProject :many
SELECT id, project_id, title, description, status, priority, assignee, due_date, artifact, created_at, updated_at FROM tasks
WHERE project_id = $1 AND status IN ('pending', 'in_progress')
ORDER BY priority ASC, created_at ASC
`

func (q *Queries) GetTasksByProject(ctx context.Context, projectID pgtype.UUID) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTasksByProject, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.Assignee,
			&i.DueDate,
			&i.Artifact,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveGoals = `-- name: ListActiveGoals :many
SELECT id, title, description, status, area, due_date, created_at, updated_at FROM goals WHERE status = 'active' ORDER BY due_date ASC NULLS LAST
`

func (q *Queries) ListActiveGoals(ctx context.Context) ([]Goal, error) {
	rows, err := q.db.Query(ctx, listActiveGoals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Goal
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Area,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveProjects = `-- name: ListActiveProjects :many
SELECT id, goal_id, name, title, description, status, area, priority, created_at, updated_at FROM projects
WHERE status = 'active'
ORDER BY priority ASC, updated_at DESC
`

func (q *Queries) ListActiveProjects(ctx context.Context) ([]Project, error) {
	rows, err := q.db.Query(ctx, listActiveProjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.GoalID,
			&i.Name,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Area,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProjectStatus = `-- name: UpdateProjectStatus :one
UPDATE projects SET status = $2, updated_at = NOW() WHERE id = $1 RETURNING id, goal_id, name, title, description, status, area, priority, created_at, updated_at
`

type UpdateProjectStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateProjectStatus(ctx context.Context, arg UpdateProjectStatusParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProjectStatus, arg.ID, arg.Status)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.Name,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Area,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :one
UPDATE tasks SET status = $2, updated_at = NOW() WHERE id = $1 RETURNING id, project_id, title, description, status, priority, assignee, due_date, artifact, created_at, updated_at
`

type UpdateTaskStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskStatus, arg.ID, arg.Status)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Assignee,
		&i.DueDate,
		&i.Artifact,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
