// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gtd.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeTask = `-- name: CompleteTask :one
UPDATE tasks SET status = 'completed', artifact = $1, updated_at = NOW()
WHERE id = $2
  AND ($3::uuid IS NULL OR workspace_id = $3)
RETURNING id, project_id, title, description, status, priority, assignee, due_date, artifact, created_at, updated_at, workspace_id, importance, context
`

type CompleteTaskParams struct {
	Artifact    pgtype.Text `json:"artifact"`
	ID          uuid.UUID   `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) CompleteTask(ctx context.Context, arg CompleteTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, completeTask, arg.Artifact, arg.ID, arg.WorkspaceID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Assignee,
		&i.DueDate,
		&i.Artifact,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
		&i.Importance,
		&i.Context,
	)
	return i, err
}

const countCompletedTasksThisWeek = `-- name: CountCompletedTasksThisWeek :one
SELECT COUNT(*) FROM tasks
WHERE status = 'completed'
  AND updated_at >= date_trunc('week', NOW())
  AND updated_at < date_trunc('week', NOW()) + interval '1 week'
  AND ($1::uuid IS NULL OR workspace_id = $1)
`

func (q *Queries) CountCompletedTasksThisWeek(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCompletedTasksThisWeek, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTotalActiveTasks = `-- name: CountTotalActiveTasks :one
SELECT COUNT(*) FROM tasks
WHERE status IN ('pending', 'in_progress')
  AND ($1::uuid IS NULL OR workspace_id = $1)
`

func (q *Queries) CountTotalActiveTasks(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTotalActiveTasks, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createActivityLog = `-- name: CreateActivityLog :one
INSERT INTO activity_log (actor, project_id, action, notes, workspace_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, actor, project_id, action, notes, created_at, workspace_id
`

type CreateActivityLogParams struct {
	Actor       string      `json:"actor"`
	ProjectID   pgtype.UUID `json:"project_id"`
	Action      string      `json:"action"`
	Notes       pgtype.Text `json:"notes"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) (ActivityLog, error) {
	row := q.db.QueryRow(ctx, createActivityLog,
		arg.Actor,
		arg.ProjectID,
		arg.Action,
		arg.Notes,
		arg.WorkspaceID,
	)
	var i ActivityLog
	err := row.Scan(
		&i.ID,
		&i.Actor,
		&i.ProjectID,
		&i.Action,
		&i.Notes,
		&i.CreatedAt,
		&i.WorkspaceID,
	)
	return i, err
}

const createGoal = `-- name: CreateGoal :one
INSERT INTO goals (title, description, area, due_date, workspace_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, title, description, status, area, due_date, created_at, updated_at, workspace_id
`

type CreateGoalParams struct {
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	Area        pgtype.Text        `json:"area"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, createGoal,
		arg.Title,
		arg.Description,
		arg.Area,
		arg.DueDate,
		arg.WorkspaceID,
	)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Area,
		&i.DueDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (goal_id, name, title, description, area, priority, workspace_id)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, goal_id, name, title, description, status, area, priority, created_at, updated_at, workspace_id
`

type CreateProjectParams struct {
	GoalID      pgtype.UUID `json:"goal_id"`
	Name        string      `json:"name"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	Area        string      `json:"area"`
	Priority    int32       `json:"priority"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.GoalID,
		arg.Name,
		arg.Title,
		arg.Description,
		arg.Area,
		arg.Priority,
		arg.WorkspaceID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.Name,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Area,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (project_id, title, description, priority, assignee, due_date, importance, context, workspace_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, project_id, title, description, status, priority, assignee, due_date, artifact, created_at, updated_at, workspace_id, importance, context
`

type CreateTaskParams struct {
	ProjectID   pgtype.UUID        `json:"project_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	Priority    int32              `json:"priority"`
	Assignee    pgtype.Text        `json:"assignee"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
	Importance  pgtype.Int2        `json:"importance"`
	Context     pgtype.Text        `json:"context"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ProjectID,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.Assignee,
		arg.DueDate,
		arg.Importance,
		arg.Context,
		arg.WorkspaceID,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Assignee,
		&i.DueDate,
		&i.Artifact,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
		&i.Importance,
		&i.Context,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks
WHERE id = $1
  AND ($2::uuid IS NULL OR workspace_id = $2)
`

type DeleteTaskParams struct {
	ID          uuid.UUID   `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

// The Go-side store wraps this in a transaction together with cleanup of
// work_session_tasks + work_sessions.current_task_id (the cascade behaviour
// previously enforced by FKs; see migration 000026 and gtd.Store.DeleteTask).
func (q *Queries) DeleteTask(ctx context.Context, arg DeleteTaskParams) error {
	_, err := q.db.Exec(ctx, deleteTask, arg.ID, arg.WorkspaceID)
	return err
}

const getAllPendingTasks = `-- name: GetAllPendingTasks :many
SELECT id, project_id, title, description, status, priority, assignee, due_date, artifact, created_at, updated_at, workspace_id, importance, context FROM tasks
WHERE status IN ('pending', 'in_progress')
  AND ($1::uuid IS NULL OR workspace_id = $1)
ORDER BY priority ASC, created_at ASC
`

func (q *Queries) GetAllPendingTasks(ctx context.Context, workspaceID pgtype.UUID) ([]Task, error) {
	rows, err := q.db.Query(ctx, getAllPendingTasks, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.Assignee,
			&i.DueDate,
			&i.Artifact,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WorkspaceID,
			&i.Importance,
			&i.Context,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, goal_id, name, title, description, status, area, priority, created_at, updated_at, workspace_id FROM projects
WHERE id = $1
  AND ($2::uuid IS NULL OR workspace_id = $2)
LIMIT 1
`

type GetProjectByIDParams struct {
	ID          uuid.UUID   `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) GetProjectByID(ctx context.Context, arg GetProjectByIDParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, arg.ID, arg.WorkspaceID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.Name,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Area,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
	)
	return i, err
}

const getProjectByName = `-- name: GetProjectByName :one
SELECT id, goal_id, name, title, description, status, area, priority, created_at, updated_at, workspace_id FROM projects
WHERE name = $1
  AND ($2::uuid IS NULL OR workspace_id = $2)
LIMIT 1
`

type GetProjectByNameParams struct {
	Name        string      `json:"name"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) GetProjectByName(ctx context.Context, arg GetProjectByNameParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByName, arg.Name, arg.WorkspaceID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.Name,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Area,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
	)
	return i, err
}

const getTasksByProject = `-- name: GetTasksByProject :many
SELECT id, project_id, title, description, status, priority, assignee, due_date, artifact, created_at, updated_at, workspace_id, importance, context FROM tasks
WHERE project_id = $1
  AND status IN ('pending', 'in_progress')
  AND ($2::uuid IS NULL OR workspace_id = $2)
ORDER BY priority ASC, created_at ASC
`

type GetTasksByProjectParams struct {
	ProjectID   pgtype.UUID `json:"project_id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) GetTasksByProject(ctx context.Context, arg GetTasksByProjectParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTasksByProject, arg.ProjectID, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.Assignee,
			&i.DueDate,
			&i.Artifact,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WorkspaceID,
			&i.Importance,
			&i.Context,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveGoals = `-- name: ListActiveGoals :many
SELECT id, title, description, status, area, due_date, created_at, updated_at, workspace_id FROM goals
WHERE status = 'active'
  AND ($1::uuid IS NULL OR workspace_id = $1)
ORDER BY due_date ASC NULLS LAST
`

func (q *Queries) ListActiveGoals(ctx context.Context, workspaceID pgtype.UUID) ([]Goal, error) {
	rows, err := q.db.Query(ctx, listActiveGoals, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Goal
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Area,
			&i.DueDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WorkspaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveProjects = `-- name: ListActiveProjects :many

SELECT id, goal_id, name, title, description, status, area, priority, created_at, updated_at, workspace_id FROM projects
WHERE status = 'active'
  AND ($1::uuid IS NULL OR workspace_id = $1)
ORDER BY priority ASC, updated_at DESC
`

// All queries take workspace_id as the named nullable arg @workspace_id.
// NULL → no filter (legacy mode); UUID → strict per-workspace scope.
func (q *Queries) ListActiveProjects(ctx context.Context, workspaceID pgtype.UUID) ([]Project, error) {
	rows, err := q.db.Query(ctx, listActiveProjects, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.GoalID,
			&i.Name,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Area,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.WorkspaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProjectStatus = `-- name: UpdateProjectStatus :one
UPDATE projects SET status = $1, updated_at = NOW()
WHERE id = $2
  AND ($3::uuid IS NULL OR workspace_id = $3)
RETURNING id, goal_id, name, title, description, status, area, priority, created_at, updated_at, workspace_id
`

type UpdateProjectStatusParams struct {
	Status      string      `json:"status"`
	ID          uuid.UUID   `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) UpdateProjectStatus(ctx context.Context, arg UpdateProjectStatusParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProjectStatus, arg.Status, arg.ID, arg.WorkspaceID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.GoalID,
		&i.Name,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Area,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
	)
	return i, err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :one
UPDATE tasks SET status = $1, updated_at = NOW()
WHERE id = $2
  AND ($3::uuid IS NULL OR workspace_id = $3)
RETURNING id, project_id, title, description, status, priority, assignee, due_date, artifact, created_at, updated_at, workspace_id, importance, context
`

type UpdateTaskStatusParams struct {
	Status      string      `json:"status"`
	ID          uuid.UUID   `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTaskStatus, arg.Status, arg.ID, arg.WorkspaceID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.Assignee,
		&i.DueDate,
		&i.Artifact,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
		&i.Importance,
		&i.Context,
	)
	return i, err
}
