// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: knowledge.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/pgvector/pgvector-go"
)

const updateKnowledgeEmbedding = `-- name: UpdateKnowledgeEmbedding :exec
UPDATE knowledge_items SET embedding = $2 WHERE id = $1
`

type UpdateKnowledgeEmbeddingParams struct {
	ID        uuid.UUID       `json:"id"`
	Embedding pgvector.Vector `json:"embedding"`
}

func (q *Queries) UpdateKnowledgeEmbedding(ctx context.Context, arg UpdateKnowledgeEmbeddingParams) error {
	_, err := q.db.Exec(ctx, updateKnowledgeEmbedding, arg.ID, arg.Embedding)
	return err
}
