// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: knowledge.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

const createKnowledgeItem = `-- name: CreateKnowledgeItem :one
INSERT INTO knowledge_items (type, title, content, url, tags, source, learning_value)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, type, title, content, url, tags, embedding, created_at, updated_at, source, learning_value, workspace_id
`

type CreateKnowledgeItemParams struct {
	Type          string      `json:"type"`
	Title         string      `json:"title"`
	Content       string      `json:"content"`
	Url           pgtype.Text `json:"url"`
	Tags          []string    `json:"tags"`
	Source        string      `json:"source"`
	LearningValue pgtype.Int4 `json:"learning_value"`
}

func (q *Queries) CreateKnowledgeItem(ctx context.Context, arg CreateKnowledgeItemParams) (KnowledgeItem, error) {
	row := q.db.QueryRow(ctx, createKnowledgeItem,
		arg.Type,
		arg.Title,
		arg.Content,
		arg.Url,
		arg.Tags,
		arg.Source,
		arg.LearningValue,
	)
	var i KnowledgeItem
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Content,
		&i.Url,
		&i.Tags,
		&i.Embedding,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.LearningValue,
		&i.WorkspaceID,
	)
	return i, err
}

const getKnowledgeByID = `-- name: GetKnowledgeByID :one
SELECT id, type, title, content, url, tags, embedding, created_at, updated_at, source, learning_value, workspace_id FROM knowledge_items WHERE id = $1
`

func (q *Queries) GetKnowledgeByID(ctx context.Context, id uuid.UUID) (KnowledgeItem, error) {
	row := q.db.QueryRow(ctx, getKnowledgeByID, id)
	var i KnowledgeItem
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Title,
		&i.Content,
		&i.Url,
		&i.Tags,
		&i.Embedding,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Source,
		&i.LearningValue,
		&i.WorkspaceID,
	)
	return i, err
}

const listKnowledge = `-- name: ListKnowledge :many
SELECT id, type, title, content, url, tags, embedding, created_at, updated_at, source, learning_value, workspace_id FROM knowledge_items ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type ListKnowledgeParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListKnowledge(ctx context.Context, arg ListKnowledgeParams) ([]KnowledgeItem, error) {
	rows, err := q.db.Query(ctx, listKnowledge, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KnowledgeItem
	for rows.Next() {
		var i KnowledgeItem
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Content,
			&i.Url,
			&i.Tags,
			&i.Embedding,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Source,
			&i.LearningValue,
			&i.WorkspaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchKnowledgeFTS = `-- name: SearchKnowledgeFTS :many
SELECT id, type, title, content, url, tags, embedding, created_at, updated_at, source, learning_value, workspace_id, ts_rank(to_tsvector('english', title || ' ' || content), plainto_tsquery('english', $1)) AS rank
FROM knowledge_items
WHERE to_tsvector('english', title || ' ' || content) @@ plainto_tsquery('english', $1)
ORDER BY rank DESC
LIMIT $2
`

type SearchKnowledgeFTSParams struct {
	PlaintoTsquery string `json:"plainto_tsquery"`
	Limit          int32  `json:"limit"`
}

type SearchKnowledgeFTSRow struct {
	ID            uuid.UUID          `json:"id"`
	Type          string             `json:"type"`
	Title         string             `json:"title"`
	Content       string             `json:"content"`
	Url           pgtype.Text        `json:"url"`
	Tags          []string           `json:"tags"`
	Embedding     pgvector.Vector    `json:"embedding"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Source        string             `json:"source"`
	LearningValue pgtype.Int4        `json:"learning_value"`
	WorkspaceID   pgtype.UUID        `json:"workspace_id"`
	Rank          float32            `json:"rank"`
}

func (q *Queries) SearchKnowledgeFTS(ctx context.Context, arg SearchKnowledgeFTSParams) ([]SearchKnowledgeFTSRow, error) {
	rows, err := q.db.Query(ctx, searchKnowledgeFTS, arg.PlaintoTsquery, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchKnowledgeFTSRow
	for rows.Next() {
		var i SearchKnowledgeFTSRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Title,
			&i.Content,
			&i.Url,
			&i.Tags,
			&i.Embedding,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Source,
			&i.LearningValue,
			&i.WorkspaceID,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateKnowledgeEmbedding = `-- name: UpdateKnowledgeEmbedding :exec
UPDATE knowledge_items SET embedding = $2 WHERE id = $1
`

type UpdateKnowledgeEmbeddingParams struct {
	ID        uuid.UUID       `json:"id"`
	Embedding pgvector.Vector `json:"embedding"`
}

func (q *Queries) UpdateKnowledgeEmbedding(ctx context.Context, arg UpdateKnowledgeEmbeddingParams) error {
	_, err := q.db.Exec(ctx, updateKnowledgeEmbedding, arg.ID, arg.Embedding)
	return err
}
