// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: learning.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createConcept = `-- name: CreateConcept :one
INSERT INTO concepts (title, content, tags) VALUES ($1, $2, $3) RETURNING id, title, content, tags, created_at, updated_at, workspace_id
`

type CreateConceptParams struct {
	Title   string   `json:"title"`
	Content string   `json:"content"`
	Tags    []string `json:"tags"`
}

func (q *Queries) CreateConcept(ctx context.Context, arg CreateConceptParams) (Concept, error) {
	row := q.db.QueryRow(ctx, createConcept, arg.Title, arg.Content, arg.Tags)
	var i Concept
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
	)
	return i, err
}

const createReviewSchedule = `-- name: CreateReviewSchedule :one
INSERT INTO review_schedule (concept_id) VALUES ($1) RETURNING id, concept_id, stability, difficulty, due_date, last_review_at, review_count, created_at, updated_at, workspace_id
`

func (q *Queries) CreateReviewSchedule(ctx context.Context, conceptID uuid.UUID) (ReviewSchedule, error) {
	row := q.db.QueryRow(ctx, createReviewSchedule, conceptID)
	var i ReviewSchedule
	err := row.Scan(
		&i.ID,
		&i.ConceptID,
		&i.Stability,
		&i.Difficulty,
		&i.DueDate,
		&i.LastReviewAt,
		&i.ReviewCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
	)
	return i, err
}

const getConceptByID = `-- name: GetConceptByID :one
SELECT id, title, content, tags, created_at, updated_at, workspace_id FROM concepts WHERE id = $1
`

func (q *Queries) GetConceptByID(ctx context.Context, id uuid.UUID) (Concept, error) {
	row := q.db.QueryRow(ctx, getConceptByID, id)
	var i Concept
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
	)
	return i, err
}

const listDueReviews = `-- name: ListDueReviews :many
SELECT c.id, c.title, c.content, c.tags, c.created_at, c.updated_at,
       rs.id as schedule_id, rs.stability, rs.difficulty, rs.due_date, rs.review_count
FROM concepts c
JOIN review_schedule rs ON rs.concept_id = c.id
WHERE rs.due_date <= NOW()
ORDER BY rs.due_date ASC
LIMIT $1
`

type ListDueReviewsRow struct {
	ID          uuid.UUID          `json:"id"`
	Title       string             `json:"title"`
	Content     string             `json:"content"`
	Tags        []string           `json:"tags"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	ScheduleID  uuid.UUID          `json:"schedule_id"`
	Stability   float64            `json:"stability"`
	Difficulty  float64            `json:"difficulty"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
	ReviewCount int32              `json:"review_count"`
}

func (q *Queries) ListDueReviews(ctx context.Context, limit int32) ([]ListDueReviewsRow, error) {
	rows, err := q.db.Query(ctx, listDueReviews, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDueReviewsRow
	for rows.Next() {
		var i ListDueReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ScheduleID,
			&i.Stability,
			&i.Difficulty,
			&i.DueDate,
			&i.ReviewCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReviewSchedule = `-- name: UpdateReviewSchedule :one
UPDATE review_schedule
SET stability = $2, difficulty = $3, due_date = $4,
    last_review_at = NOW(), review_count = review_count + 1, updated_at = NOW()
WHERE id = $1 RETURNING id, concept_id, stability, difficulty, due_date, last_review_at, review_count, created_at, updated_at, workspace_id
`

type UpdateReviewScheduleParams struct {
	ID         uuid.UUID          `json:"id"`
	Stability  float64            `json:"stability"`
	Difficulty float64            `json:"difficulty"`
	DueDate    pgtype.Timestamptz `json:"due_date"`
}

func (q *Queries) UpdateReviewSchedule(ctx context.Context, arg UpdateReviewScheduleParams) (ReviewSchedule, error) {
	row := q.db.QueryRow(ctx, updateReviewSchedule,
		arg.ID,
		arg.Stability,
		arg.Difficulty,
		arg.DueDate,
	)
	var i ReviewSchedule
	err := row.Scan(
		&i.ID,
		&i.ConceptID,
		&i.Stability,
		&i.Difficulty,
		&i.DueDate,
		&i.LastReviewAt,
		&i.ReviewCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
	)
	return i, err
}
