// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: learning.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createConcept = `-- name: CreateConcept :one
INSERT INTO concepts (title, content, tags, workspace_id)
VALUES ($1, $2, $3, $4)
RETURNING id, title, content, tags, created_at, updated_at, workspace_id, status
`

type CreateConceptParams struct {
	Title       string      `json:"title"`
	Content     string      `json:"content"`
	Tags        []string    `json:"tags"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) CreateConcept(ctx context.Context, arg CreateConceptParams) (Concept, error) {
	row := q.db.QueryRow(ctx, createConcept,
		arg.Title,
		arg.Content,
		arg.Tags,
		arg.WorkspaceID,
	)
	var i Concept
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
		&i.Status,
	)
	return i, err
}

const createReviewSchedule = `-- name: CreateReviewSchedule :one
INSERT INTO review_schedule (concept_id, workspace_id)
VALUES ($1, $2)
RETURNING id, concept_id, stability, difficulty, due_date, last_review_at, review_count, created_at, updated_at, workspace_id
`

type CreateReviewScheduleParams struct {
	ConceptID   uuid.UUID   `json:"concept_id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) CreateReviewSchedule(ctx context.Context, arg CreateReviewScheduleParams) (ReviewSchedule, error) {
	row := q.db.QueryRow(ctx, createReviewSchedule, arg.ConceptID, arg.WorkspaceID)
	var i ReviewSchedule
	err := row.Scan(
		&i.ID,
		&i.ConceptID,
		&i.Stability,
		&i.Difficulty,
		&i.DueDate,
		&i.LastReviewAt,
		&i.ReviewCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
	)
	return i, err
}

const getConceptByID = `-- name: GetConceptByID :one
SELECT id, title, content, tags, created_at, updated_at, workspace_id, status FROM concepts
WHERE id = $1
  AND ($2::uuid IS NULL OR workspace_id = $2)
`

type GetConceptByIDParams struct {
	ID          uuid.UUID   `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) GetConceptByID(ctx context.Context, arg GetConceptByIDParams) (Concept, error) {
	row := q.db.QueryRow(ctx, getConceptByID, arg.ID, arg.WorkspaceID)
	var i Concept
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
		&i.Status,
	)
	return i, err
}

const listConceptsForAIReview = `-- name: ListConceptsForAIReview :many
SELECT c.id, c.title, c.content, rs.review_count, rs.stability
FROM concepts c
JOIN review_schedule rs ON rs.concept_id = c.id
WHERE c.status = 'active'
  AND rs.review_count >= $1
  AND ($2::uuid IS NULL OR c.workspace_id = $2)
ORDER BY rs.review_count DESC
`

type ListConceptsForAIReviewParams struct {
	MinReviewCount int32       `json:"min_review_count"`
	WorkspaceID    pgtype.UUID `json:"workspace_id"`
}

type ListConceptsForAIReviewRow struct {
	ID          uuid.UUID `json:"id"`
	Title       string    `json:"title"`
	Content     string    `json:"content"`
	ReviewCount int32     `json:"review_count"`
	Stability   float64   `json:"stability"`
}

func (q *Queries) ListConceptsForAIReview(ctx context.Context, arg ListConceptsForAIReviewParams) ([]ListConceptsForAIReviewRow, error) {
	rows, err := q.db.Query(ctx, listConceptsForAIReview, arg.MinReviewCount, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConceptsForAIReviewRow
	for rows.Next() {
		var i ListConceptsForAIReviewRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.ReviewCount,
			&i.Stability,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDueReviews = `-- name: ListDueReviews :many
SELECT c.id, c.title, c.content, c.tags, c.created_at, c.updated_at, c.status,
       rs.id as schedule_id, rs.stability, rs.difficulty, rs.due_date, rs.review_count
FROM concepts c
JOIN review_schedule rs ON rs.concept_id = c.id
WHERE rs.due_date <= NOW()
  AND c.status = 'active'
  AND ($1::uuid IS NULL OR c.workspace_id = $1)
ORDER BY rs.due_date ASC
LIMIT $2
`

type ListDueReviewsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	LimitN      int32       `json:"limit_n"`
}

type ListDueReviewsRow struct {
	ID          uuid.UUID          `json:"id"`
	Title       string             `json:"title"`
	Content     string             `json:"content"`
	Tags        []string           `json:"tags"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Status      string             `json:"status"`
	ScheduleID  uuid.UUID          `json:"schedule_id"`
	Stability   float64            `json:"stability"`
	Difficulty  float64            `json:"difficulty"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
	ReviewCount int32              `json:"review_count"`
}

func (q *Queries) ListDueReviews(ctx context.Context, arg ListDueReviewsParams) ([]ListDueReviewsRow, error) {
	rows, err := q.db.Query(ctx, listDueReviews, arg.WorkspaceID, arg.LimitN)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDueReviewsRow
	for rows.Next() {
		var i ListDueReviewsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.Tags,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.ScheduleID,
			&i.Stability,
			&i.Difficulty,
			&i.DueDate,
			&i.ReviewCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConceptStatus = `-- name: UpdateConceptStatus :one
UPDATE concepts
SET status = $1, updated_at = NOW()
WHERE id = $2
RETURNING id, title, content, tags, created_at, updated_at, workspace_id, status
`

type UpdateConceptStatusParams struct {
	Status string    `json:"status"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) UpdateConceptStatus(ctx context.Context, arg UpdateConceptStatusParams) (Concept, error) {
	row := q.db.QueryRow(ctx, updateConceptStatus, arg.Status, arg.ID)
	var i Concept
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Tags,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
		&i.Status,
	)
	return i, err
}

const updateReviewSchedule = `-- name: UpdateReviewSchedule :one
UPDATE review_schedule
SET stability = $1, difficulty = $2, due_date = $3,
    last_review_at = NOW(), review_count = review_count + 1, updated_at = NOW()
WHERE id = $4
  AND ($5::uuid IS NULL OR workspace_id = $5)
RETURNING id, concept_id, stability, difficulty, due_date, last_review_at, review_count, created_at, updated_at, workspace_id
`

type UpdateReviewScheduleParams struct {
	Stability   float64            `json:"stability"`
	Difficulty  float64            `json:"difficulty"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
	ID          uuid.UUID          `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
}

func (q *Queries) UpdateReviewSchedule(ctx context.Context, arg UpdateReviewScheduleParams) (ReviewSchedule, error) {
	row := q.db.QueryRow(ctx, updateReviewSchedule,
		arg.Stability,
		arg.Difficulty,
		arg.DueDate,
		arg.ID,
		arg.WorkspaceID,
	)
	var i ReviewSchedule
	err := row.Scan(
		&i.ID,
		&i.ConceptID,
		&i.Stability,
		&i.Difficulty,
		&i.DueDate,
		&i.LastReviewAt,
		&i.ReviewCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.WorkspaceID,
	)
	return i, err
}
