// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type ActivityLog struct {
	ID          uuid.UUID          `json:"id"`
	Actor       string             `json:"actor"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	Action      string             `json:"action"`
	Notes       pgtype.Text        `json:"notes"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
}

type Concept struct {
	ID          uuid.UUID          `json:"id"`
	Title       string             `json:"title"`
	Content     string             `json:"content"`
	Tags        []string           `json:"tags"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Status      string             `json:"status"`
	// Ebbinghaus decay fields (migration 000019)
	Importance     float64            `json:"importance"`
	RecallCount    int32              `json:"recall_count"`
	LastRecalledAt pgtype.Timestamptz `json:"last_recalled_at"`
	BaseLambda     float64            `json:"base_lambda"`
	ArchivedAt     pgtype.Timestamptz `json:"archived_at"`
}

type Decision struct {
	ID           uuid.UUID          `json:"id"`
	ProjectID    pgtype.UUID        `json:"project_id"`
	RepoName     pgtype.Text        `json:"repo_name"`
	Title        string             `json:"title"`
	Context      string             `json:"context"`
	Decision     string             `json:"decision"`
	Rationale    string             `json:"rationale"`
	Alternatives pgtype.Text        `json:"alternatives"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	WorkspaceID  pgtype.UUID        `json:"workspace_id"`
}

type Goal struct {
	ID          uuid.UUID          `json:"id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	Status      string             `json:"status"`
	Area        pgtype.Text        `json:"area"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
}

type KnowledgeItem struct {
	ID            uuid.UUID          `json:"id"`
	Type          string             `json:"type"`
	Title         string             `json:"title"`
	Content       string             `json:"content"`
	Url           pgtype.Text        `json:"url"`
	Tags          []string           `json:"tags"`
	Embedding     pgvector.Vector    `json:"embedding"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Source        string             `json:"source"`
	LearningValue pgtype.Int4        `json:"learning_value"`
	WorkspaceID   pgtype.UUID        `json:"workspace_id"`
	// Ebbinghaus decay fields (migration 000019)
	Importance     float64            `json:"importance"`
	RecallCount    int32              `json:"recall_count"`
	LastRecalledAt pgtype.Timestamptz `json:"last_recalled_at"`
	BaseLambda     float64            `json:"base_lambda"`
	ArchivedAt     pgtype.Timestamptz `json:"archived_at"`
}

type PendingProposal struct {
	ID          uuid.UUID          `json:"id"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Type        string             `json:"type"`
	Payload     []byte             `json:"payload"`
	Status      string             `json:"status"`
	ProposedBy  pgtype.Text        `json:"proposed_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ResolvedAt  pgtype.Timestamptz `json:"resolved_at"`
}

type Project struct {
	ID          uuid.UUID          `json:"id"`
	GoalID      pgtype.UUID        `json:"goal_id"`
	Name        string             `json:"name"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	Status      string             `json:"status"`
	Area        string             `json:"area"`
	Priority    int32              `json:"priority"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
}

type Repo struct {
	ID              uuid.UUID          `json:"id"`
	Name            string             `json:"name"`
	Path            pgtype.Text        `json:"path"`
	Description     pgtype.Text        `json:"description"`
	Language        pgtype.Text        `json:"language"`
	Status          string             `json:"status"`
	CurrentBranch   pgtype.Text        `json:"current_branch"`
	KnownIssues     []string           `json:"known_issues"`
	NextPlannedStep pgtype.Text        `json:"next_planned_step"`
	LastActivity    pgtype.Timestamptz `json:"last_activity"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
}

type ReviewSchedule struct {
	ID           uuid.UUID          `json:"id"`
	ConceptID    uuid.UUID          `json:"concept_id"`
	Stability    float64            `json:"stability"`
	Difficulty   float64            `json:"difficulty"`
	DueDate      pgtype.Timestamptz `json:"due_date"`
	LastReviewAt pgtype.Timestamptz `json:"last_review_at"`
	ReviewCount  int32              `json:"review_count"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	WorkspaceID  pgtype.UUID        `json:"workspace_id"`
}

type SessionHandoff struct {
	ID             uuid.UUID          `json:"id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	RepoName       pgtype.Text        `json:"repo_name"`
	Intent         string             `json:"intent"`
	ContextSummary pgtype.Text        `json:"context_summary"`
	ResolvedAt     pgtype.Timestamptz `json:"resolved_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	WorkspaceID    pgtype.UUID        `json:"workspace_id"`
}

type Task struct {
	ID          uuid.UUID          `json:"id"`
	ProjectID   pgtype.UUID        `json:"project_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	Status      string             `json:"status"`
	Priority    int32              `json:"priority"`
	Assignee    pgtype.Text        `json:"assignee"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
	Artifact    pgtype.Text        `json:"artifact"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Importance  pgtype.Int2        `json:"importance"`
	Context     pgtype.Text        `json:"context"`
}
