// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: proposal.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPendingProposal = `-- name: CreatePendingProposal :one
INSERT INTO pending_proposals (workspace_id, type, payload, proposed_by)
VALUES ($1, $2, $3, $4)
RETURNING id, workspace_id, type, payload, status, proposed_by, created_at, resolved_at
`

type CreatePendingProposalParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Type        string      `json:"type"`
	Payload     []byte      `json:"payload"`
	ProposedBy  pgtype.Text `json:"proposed_by"`
}

func (q *Queries) CreatePendingProposal(ctx context.Context, arg CreatePendingProposalParams) (PendingProposal, error) {
	row := q.db.QueryRow(ctx, createPendingProposal,
		arg.WorkspaceID,
		arg.Type,
		arg.Payload,
		arg.ProposedBy,
	)
	var i PendingProposal
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.ProposedBy,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getPendingProposal = `-- name: GetPendingProposal :one
SELECT id, workspace_id, type, payload, status, proposed_by, created_at, resolved_at FROM pending_proposals
WHERE id = $1
  AND ($2::uuid IS NULL OR workspace_id = $2)
LIMIT 1
`

type GetPendingProposalParams struct {
	ID          uuid.UUID   `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) GetPendingProposal(ctx context.Context, arg GetPendingProposalParams) (PendingProposal, error) {
	row := q.db.QueryRow(ctx, getPendingProposal, arg.ID, arg.WorkspaceID)
	var i PendingProposal
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.ProposedBy,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const listPendingProposals = `-- name: ListPendingProposals :many
SELECT id, workspace_id, type, payload, status, proposed_by, created_at, resolved_at FROM pending_proposals
WHERE status = 'pending'
  AND ($1::uuid IS NULL OR workspace_id = $1)
ORDER BY created_at DESC
`

func (q *Queries) ListPendingProposals(ctx context.Context, workspaceID pgtype.UUID) ([]PendingProposal, error) {
	rows, err := q.db.Query(ctx, listPendingProposals, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PendingProposal
	for rows.Next() {
		var i PendingProposal
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Type,
			&i.Payload,
			&i.Status,
			&i.ProposedBy,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolvePendingProposal = `-- name: ResolvePendingProposal :one
UPDATE pending_proposals
SET status = $1, resolved_at = NOW()
WHERE id = $2
  AND status = 'pending'
  AND ($3::uuid IS NULL OR workspace_id = $3)
RETURNING id, workspace_id, type, payload, status, proposed_by, created_at, resolved_at
`

type ResolvePendingProposalParams struct {
	Status      string      `json:"status"`
	ID          uuid.UUID   `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) ResolvePendingProposal(ctx context.Context, arg ResolvePendingProposalParams) (PendingProposal, error) {
	row := q.db.QueryRow(ctx, resolvePendingProposal, arg.Status, arg.ID, arg.WorkspaceID)
	var i PendingProposal
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Type,
		&i.Payload,
		&i.Status,
		&i.ProposedBy,
		&i.CreatedAt,
		&i.ResolvedAt,
	)
	return i, err
}
