// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CompleteTask(ctx context.Context, arg CompleteTaskParams) (Task, error)
	CountCompletedTasksThisWeek(ctx context.Context) (int64, error)
	CountTotalActiveTasks(ctx context.Context) (int64, error)
	CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) (ActivityLog, error)
	CreateDecision(ctx context.Context, arg CreateDecisionParams) (Decision, error)
	CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateSessionHandoff(ctx context.Context, arg CreateSessionHandoffParams) (SessionHandoff, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	DeleteTask(ctx context.Context, id uuid.UUID) error
	GetAllPendingTasks(ctx context.Context) ([]Task, error)
	GetLatestUnresolvedHandoff(ctx context.Context) (SessionHandoff, error)
	GetProjectByName(ctx context.Context, name string) (Project, error)
	GetRepoByName(ctx context.Context, name string) (Repo, error)
	GetTasksByProject(ctx context.Context, projectID pgtype.UUID) ([]Task, error)
	ListActiveGoals(ctx context.Context) ([]Goal, error)
	ListActiveProjects(ctx context.Context) ([]Project, error)
	ListActiveRepos(ctx context.Context) ([]Repo, error)
	ListDecisionsByProject(ctx context.Context, arg ListDecisionsByProjectParams) ([]Decision, error)
	ListDecisionsByRepo(ctx context.Context, arg ListDecisionsByRepoParams) ([]Decision, error)
	ResolveHandoff(ctx context.Context, id uuid.UUID) (int64, error)
	UpdateProjectStatus(ctx context.Context, arg UpdateProjectStatusParams) (Project, error)
	UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error)
	UpsertRepo(ctx context.Context, arg UpsertRepoParams) (Repo, error)
}

var _ Querier = (*Queries)(nil)
