// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CompleteTask(ctx context.Context, arg CompleteTaskParams) (Task, error)
	CountCompletedTasksThisWeek(ctx context.Context) (int64, error)
	CountTotalActiveTasks(ctx context.Context) (int64, error)
	CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) (ActivityLog, error)
	CreateConcept(ctx context.Context, arg CreateConceptParams) (Concept, error)
	CreateDecision(ctx context.Context, arg CreateDecisionParams) (Decision, error)
	CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error)
	CreateKnowledgeItem(ctx context.Context, arg CreateKnowledgeItemParams) (KnowledgeItem, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateReviewSchedule(ctx context.Context, conceptID uuid.UUID) (ReviewSchedule, error)
	CreateSessionHandoff(ctx context.Context, arg CreateSessionHandoffParams) (SessionHandoff, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	DeleteTask(ctx context.Context, id uuid.UUID) error
	GetAllPendingTasks(ctx context.Context) ([]Task, error)
	GetConceptByID(ctx context.Context, id uuid.UUID) (Concept, error)
	GetKnowledgeByID(ctx context.Context, id uuid.UUID) (KnowledgeItem, error)
	GetLatestUnresolvedHandoff(ctx context.Context) (SessionHandoff, error)
	GetProjectByName(ctx context.Context, name string) (Project, error)
	GetRepoByName(ctx context.Context, name string) (Repo, error)
	GetTasksByProject(ctx context.Context, projectID pgtype.UUID) ([]Task, error)
	ListActiveGoals(ctx context.Context) ([]Goal, error)
	ListActiveProjects(ctx context.Context) ([]Project, error)
	ListActiveRepos(ctx context.Context) ([]Repo, error)
	ListDecisionsByProject(ctx context.Context, arg ListDecisionsByProjectParams) ([]Decision, error)
	ListDecisionsByRepo(ctx context.Context, arg ListDecisionsByRepoParams) ([]Decision, error)
	ListDueReviews(ctx context.Context, limit int32) ([]ListDueReviewsRow, error)
	ListKnowledge(ctx context.Context, arg ListKnowledgeParams) ([]KnowledgeItem, error)
	ResolveHandoff(ctx context.Context, id uuid.UUID) (int64, error)
	SearchKnowledgeFTS(ctx context.Context, arg SearchKnowledgeFTSParams) ([]SearchKnowledgeFTSRow, error)
	UpdateKnowledgeEmbedding(ctx context.Context, arg UpdateKnowledgeEmbeddingParams) error
	UpdateProjectStatus(ctx context.Context, arg UpdateProjectStatusParams) (Project, error)
	UpdateReviewSchedule(ctx context.Context, arg UpdateReviewScheduleParams) (ReviewSchedule, error)
	UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error)
	UpsertRepo(ctx context.Context, arg UpsertRepoParams) (Repo, error)
}

var _ Querier = (*Queries)(nil)
