// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Atomically sets status to in_progress only when the current status is not
	// already in_progress, preventing duplicate activity_log rows on concurrent calls.
	// Returns pgx.ErrNoRows when the task is already in_progress or not found.
	BeginTaskStatus(ctx context.Context, arg BeginTaskStatusParams) (Task, error)
	CompleteTask(ctx context.Context, arg CompleteTaskParams) (Task, error)
	CountCompletedTasksThisWeek(ctx context.Context, workspaceID pgtype.UUID) (int64, error)
	// Returns count of tasks that are "relevant to this week":
	// (1) completed this week, OR
	// (2) pending/in_progress AND (due_date this week OR created this week)
	CountWeeklyRelevantTasks(ctx context.Context, workspaceID pgtype.UUID) (int64, error)
	CreateActivityLog(ctx context.Context, arg CreateActivityLogParams) (ActivityLog, error)
	CreateConcept(ctx context.Context, arg CreateConceptParams) (Concept, error)
	CreateDecision(ctx context.Context, arg CreateDecisionParams) (Decision, error)
	CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error)
	CreatePendingProposal(ctx context.Context, arg CreatePendingProposalParams) (PendingProposal, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateReviewSchedule(ctx context.Context, arg CreateReviewScheduleParams) (ReviewSchedule, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	// The Go-side store wraps this in a transaction together with cleanup of
	// work_session_tasks + work_sessions.current_task_id (the cascade behaviour
	// previously enforced by FKs; see migration 000026 and gtd.Store.DeleteTask).
	DeleteTask(ctx context.Context, arg DeleteTaskParams) error
	GetAllPendingTasks(ctx context.Context, workspaceID pgtype.UUID) ([]Task, error)
	GetPendingProposal(ctx context.Context, arg GetPendingProposalParams) (PendingProposal, error)
	GetProjectByID(ctx context.Context, arg GetProjectByIDParams) (Project, error)
	GetProjectByName(ctx context.Context, arg GetProjectByNameParams) (Project, error)
	GetRepoByName(ctx context.Context, arg GetRepoByNameParams) (Repo, error)
	GetTasksByProject(ctx context.Context, arg GetTasksByProjectParams) ([]Task, error)
	HandoffsSince(ctx context.Context, arg HandoffsSinceParams) ([]SessionHandoff, error)
	ListActiveGoals(ctx context.Context, workspaceID pgtype.UUID) ([]Goal, error)
	// All queries take workspace_id as the named nullable arg @workspace_id.
	// NULL → no filter (legacy mode); UUID → strict per-workspace scope.
	ListActiveProjects(ctx context.Context, workspaceID pgtype.UUID) ([]Project, error)
	ListActiveRepos(ctx context.Context, workspaceID pgtype.UUID) ([]Repo, error)
	ListAllDecisions(ctx context.Context, arg ListAllDecisionsParams) ([]Decision, error)
	ListConcepts(ctx context.Context, arg ListConceptsParams) ([]Concept, error)
	ListConceptsForAIReview(ctx context.Context, arg ListConceptsForAIReviewParams) ([]ListConceptsForAIReviewRow, error)
	ListDecisionsByProject(ctx context.Context, arg ListDecisionsByProjectParams) ([]Decision, error)
	ListDecisionsByRepo(ctx context.Context, arg ListDecisionsByRepoParams) ([]Decision, error)
	ListDecisionsByTaskID(ctx context.Context, arg ListDecisionsByTaskIDParams) ([]Decision, error)
	// P3.0a Stage B: source-filtered read path for MCP list_decisions.
	// project_id and repo_name are mutually exclusive at the application layer
	// (decision.ListParams.Validate) — this query accepts both narg'd so a nil
	// one is a no-op filter, but callers never pass both non-nil.
	// Source is filtered BEFORE ORDER/LIMIT so the limit isn't consumed by rows
	// that get excluded.
	ListDecisionsFiltered(ctx context.Context, arg ListDecisionsFilteredParams) ([]Decision, error)
	ListDueReviews(ctx context.Context, arg ListDueReviewsParams) ([]ListDueReviewsRow, error)
	ListPendingProposals(ctx context.Context, workspaceID pgtype.UUID) ([]PendingProposal, error)
	// All-statuses variant of GetTasksByProject. Used by the ProjectDetailPage to
	// render both the "open" and the "completed/cancelled" sections; the default
	// GetTasksByProject query stays active-only so existing GTD list pages don't
	// regress. Ordering: newest activity first via COALESCE(updated_at, created_at)
	// DESC so completed rows surface in roughly the order they were finished.
	ListProjectTasksAllStatuses(ctx context.Context, arg ListProjectTasksAllStatusesParams) ([]Task, error)
	ResolveHandoff(ctx context.Context, arg ResolveHandoffParams) (int64, error)
	ResolvePendingProposal(ctx context.Context, arg ResolvePendingProposalParams) (PendingProposal, error)
	ReviewedSince(ctx context.Context, arg ReviewedSinceParams) ([]ReviewedSinceRow, error)
	SetTaskVisionItemID(ctx context.Context, arg SetTaskVisionItemIDParams) (Task, error)
	UpdateConceptStatus(ctx context.Context, arg UpdateConceptStatusParams) (Concept, error)
	UpdateGoal(ctx context.Context, arg UpdateGoalParams) (Goal, error)
	UpdateKnowledgeEmbedding(ctx context.Context, arg UpdateKnowledgeEmbeddingParams) error
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error)
	UpdateProjectStatus(ctx context.Context, arg UpdateProjectStatusParams) (Project, error)
	UpdateReviewSchedule(ctx context.Context, arg UpdateReviewScheduleParams) (ReviewSchedule, error)
	UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) (Task, error)
	UpsertRepo(ctx context.Context, arg UpsertRepoParams) (Repo, error)
}

var _ Querier = (*Queries)(nil)
