// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const handoffsSince = `-- name: HandoffsSince :many
SELECT id, project_id, repo_name, intent, context_summary, resolved_at, created_at, workspace_id, summary_text, embedding, next_actions, embedding_provider, embedding_model, embedding_dim FROM session_handoffs
WHERE ($1::uuid IS NULL OR workspace_id = $1)
  AND (created_at >= $2 OR (resolved_at IS NOT NULL AND resolved_at >= $2))
ORDER BY created_at DESC
LIMIT $3
`

type HandoffsSinceParams struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	Since       pgtype.Timestamptz `json:"since"`
	LimitN      int32              `json:"limit_n"`
}

func (q *Queries) HandoffsSince(ctx context.Context, arg HandoffsSinceParams) ([]SessionHandoff, error) {
	rows, err := q.db.Query(ctx, handoffsSince, arg.WorkspaceID, arg.Since, arg.LimitN)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionHandoff
	for rows.Next() {
		var i SessionHandoff
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.RepoName,
			&i.Intent,
			&i.ContextSummary,
			&i.ResolvedAt,
			&i.CreatedAt,
			&i.WorkspaceID,
			&i.SummaryText,
			&i.Embedding,
			&i.NextActions,
			&i.EmbeddingProvider,
			&i.EmbeddingModel,
			&i.EmbeddingDim,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveHandoff = `-- name: ResolveHandoff :execrows
UPDATE session_handoffs SET resolved_at = NOW()
WHERE id = $1
  AND resolved_at IS NULL
  AND ($2::uuid IS NULL OR workspace_id = $2)
`

type ResolveHandoffParams struct {
	ID          uuid.UUID   `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) ResolveHandoff(ctx context.Context, arg ResolveHandoffParams) (int64, error) {
	result, err := q.db.Exec(ctx, resolveHandoff, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
