// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: session.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSessionHandoff = `-- name: CreateSessionHandoff :one
INSERT INTO session_handoffs (project_id, repo_name, intent, context_summary, workspace_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, project_id, repo_name, intent, context_summary, resolved_at, created_at, workspace_id
`

type CreateSessionHandoffParams struct {
	ProjectID      pgtype.UUID `json:"project_id"`
	RepoName       pgtype.Text `json:"repo_name"`
	Intent         string      `json:"intent"`
	ContextSummary pgtype.Text `json:"context_summary"`
	WorkspaceID    pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) CreateSessionHandoff(ctx context.Context, arg CreateSessionHandoffParams) (SessionHandoff, error) {
	row := q.db.QueryRow(ctx, createSessionHandoff,
		arg.ProjectID,
		arg.RepoName,
		arg.Intent,
		arg.ContextSummary,
		arg.WorkspaceID,
	)
	var i SessionHandoff
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RepoName,
		&i.Intent,
		&i.ContextSummary,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.WorkspaceID,
	)
	return i, err
}

const getLatestUnresolvedHandoff = `-- name: GetLatestUnresolvedHandoff :one
SELECT id, project_id, repo_name, intent, context_summary, resolved_at, created_at, workspace_id FROM session_handoffs
WHERE resolved_at IS NULL
  AND ($1::uuid IS NULL OR workspace_id = $1)
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestUnresolvedHandoff(ctx context.Context, workspaceID pgtype.UUID) (SessionHandoff, error) {
	row := q.db.QueryRow(ctx, getLatestUnresolvedHandoff, workspaceID)
	var i SessionHandoff
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.RepoName,
		&i.Intent,
		&i.ContextSummary,
		&i.ResolvedAt,
		&i.CreatedAt,
		&i.WorkspaceID,
	)
	return i, err
}

const resolveHandoff = `-- name: ResolveHandoff :execrows
UPDATE session_handoffs SET resolved_at = NOW()
WHERE id = $1
  AND ($2::uuid IS NULL OR workspace_id = $2)
`

type ResolveHandoffParams struct {
	ID          uuid.UUID   `json:"id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) ResolveHandoff(ctx context.Context, arg ResolveHandoffParams) (int64, error) {
	result, err := q.db.Exec(ctx, resolveHandoff, arg.ID, arg.WorkspaceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
