// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRepoByName = `-- name: GetRepoByName :one
SELECT id, name, path, description, language, status, current_branch, known_issues, next_planned_step, last_activity, created_at, updated_at FROM repos WHERE name = $1 LIMIT 1
`

func (q *Queries) GetRepoByName(ctx context.Context, name string) (Repo, error) {
	row := q.db.QueryRow(ctx, getRepoByName, name)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.Description,
		&i.Language,
		&i.Status,
		&i.CurrentBranch,
		&i.KnownIssues,
		&i.NextPlannedStep,
		&i.LastActivity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveRepos = `-- name: ListActiveRepos :many
SELECT id, name, path, description, language, status, current_branch, known_issues, next_planned_step, last_activity, created_at, updated_at FROM repos WHERE status = 'active' ORDER BY last_activity DESC NULLS LAST, name ASC
`

func (q *Queries) ListActiveRepos(ctx context.Context) ([]Repo, error) {
	rows, err := q.db.Query(ctx, listActiveRepos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repo
	for rows.Next() {
		var i Repo
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Path,
			&i.Description,
			&i.Language,
			&i.Status,
			&i.CurrentBranch,
			&i.KnownIssues,
			&i.NextPlannedStep,
			&i.LastActivity,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRepo = `-- name: UpsertRepo :one
INSERT INTO repos (name, path, description, language, current_branch, known_issues, next_planned_step, last_activity)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (name) DO UPDATE SET
    path = EXCLUDED.path,
    description = EXCLUDED.description,
    language = EXCLUDED.language,
    current_branch = EXCLUDED.current_branch,
    known_issues = EXCLUDED.known_issues,
    next_planned_step = EXCLUDED.next_planned_step,
    last_activity = EXCLUDED.last_activity,
    updated_at = NOW()
RETURNING id, name, path, description, language, status, current_branch, known_issues, next_planned_step, last_activity, created_at, updated_at
`

type UpsertRepoParams struct {
	Name            string             `json:"name"`
	Path            pgtype.Text        `json:"path"`
	Description     pgtype.Text        `json:"description"`
	Language        pgtype.Text        `json:"language"`
	CurrentBranch   pgtype.Text        `json:"current_branch"`
	KnownIssues     []string           `json:"known_issues"`
	NextPlannedStep pgtype.Text        `json:"next_planned_step"`
	LastActivity    pgtype.Timestamptz `json:"last_activity"`
}

func (q *Queries) UpsertRepo(ctx context.Context, arg UpsertRepoParams) (Repo, error) {
	row := q.db.QueryRow(ctx, upsertRepo,
		arg.Name,
		arg.Path,
		arg.Description,
		arg.Language,
		arg.CurrentBranch,
		arg.KnownIssues,
		arg.NextPlannedStep,
		arg.LastActivity,
	)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Path,
		&i.Description,
		&i.Language,
		&i.Status,
		&i.CurrentBranch,
		&i.KnownIssues,
		&i.NextPlannedStep,
		&i.LastActivity,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
